Informational:
  100:
    message: Continue
  101:
    message: Switching Protocols
  102:
    message: Processing
Success:
  200:
    message: OK
  201:
    message: Created
  202:
    message: Accepted
  203:
    message: Non-Authoritative Information
  204:
    message: No Content
  205:
    message: Reset Content
  206:
    message: Partial Content
  207:
    message: Multi-Status
Redirection:
  300:
    message: Multiple Choices
  301:
    message: Moved Permanently
  302:
    message: Found
  303:
    message: See Other
  304:
    message: Not Modified
  305:
    message: Use Proxy
  306:
    message: Switch Proxy
  307:
    message: Temporary Redirect
Client_Error:
  400:
    message: Bad Request
  401:
    message: Unauthorized
  402:
    message: Payment Required
  403:
    message: Forbidden
  404:
    message: Resource Not Found
  405:
    message: Method Not Allowed
  406:
    message: Not Acceptable
  407:
    message: Proxy Authentication Required
  408:
    message: Request Timeout
  409:
    message: Conflict
  410:
    message: Gone
  411:
    message: Length Required
  412:
    message: Precondition Failed
  413:
    message: Request Entity Too Large
  414:
    message: Request-URI Too Long
  415:
    message: Unsupported Media Type
  416:
    message: Requested Range Not Satisfiable
  417:
    message: Expectation Failed
  418:
    message: Im A Teapot
  421:
    message: Too Many Connections From This IP
  422:
    message: Unprocessable Entity
  423:
    message: Locked
  424:
    message: Failed Dependency
  425:
    message: Unordered Collection
  426:
    message: Upgrade Required
  449:
    message: Retry With
  450:
    message: Blocked By Windows Parental Controls
Server_Error:
  500:
    message: Internal Server Error
  501:
    message: Not Implemented
  502:
    message: Bad Gateway
  503:
    message: Service Unavailable
  504:
    message: Gateway Timeout
  505:
    message: HTTP Version Not Supported
  506:
    message: Variant Also Negotiates
  507:
    message: Insufficient Storage
  509:
    message: Bandwidth Limit Exceeded
  510:
    message: Not Extended